### ISSUE TITLE
Feature: "Share" button for replies.

### ISSUE THREAD

**Issue by usandfriends** [cpluspluscom/EnhancedCpp.com#11]
Like the title says, I would like to see a share button for each reply so I don't have to Inspect Element to get the post ID.

**Comment by LB--** [comment]
This already exists:
![image](https://cloud.githubusercontent.com/assets/1296838/10298793/3d6805a0-6ba8-11e5-8886-91a94b412f62.png)
It's the little chain - just click it.

**Comment by usandfriends** [comment]
Whoah, did not see that. Thanks!
