### ISSUE TITLE
Auto-save answer.

### ISSUE THREAD

**Issue by usandfriends** [cpluspluscom/EnhancedCpp.com#7]
Auto-save answers so if you accidentally leave a page and come back, you won't lose all your work.

**Comment by EssGeeEich** [comment]
I can't manually check it right now, but there's a couple of lines you can
erase somewhere that should fix both this AND another bug. This script file
should only have those two lines of code or so. Note that if you erase that
file you also need to edit manifest.json. ~email reply
Il 07/feb/2015 07:56 "us͡an̸df͘rien͜ds͠" <notifications@github.com> ha
scritto:
